version: '3'

services: 
  php:
    build: .
    ports:
     - "80:80"
     - "444:444"
    volumes:
     - ./:/var/www/html 
    links:
     - db
  db:
    image: mysql:5.6
    volumes:
     - /var/lib/mysql
    environment:
      MYSQL_DATABASE: 'phpcrud'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '9906:3306'